In [1]:
import numpy as np
#prueba

In [2]:
my_list = [1, 2, 3] 
#we create a list, which is deifferent from a tupple.
arr = np.array(my_list)
#we turn it into a numpy array
my_matrice = [[1,2,3], [4,5,6], [7,8,9]]
#we create a 2d list or a matrice
np.array(my_matrice)
#we turn it into a np 2d array
#we can run this line of code with shift+enter. where shift is the upwards arrow 
#in the keyboard

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#for inserting a new cell alt+enter

For seeing the documentation of a function shift+tab

##### Create an array using np.arrange(start, stop, step)

In [8]:
np.arange(0, 10, 1,  dtype=None)#(start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

For generate an array of zeros

In [9]:
np.zeros((2,3)) #it creates a tupple of zeros 2 rows nd 3 cols

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

LINSPACE generates an array evenly spaced. 

In [11]:
np.linspace(0, 20, 50) # (start, stop, number of points)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

GENERATE an identity matrice

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create matrices populated by random numbers

In [13]:
np.random.rand(5,5)#generates a matrice with random numbers between 0 and 1

array([[0.13265446, 0.15460302, 0.1766952 , 0.82320176, 0.41425657],
       [0.14631959, 0.79108204, 0.58336076, 0.71131309, 0.29132122],
       [0.00451905, 0.12061771, 0.00876709, 0.09326393, 0.64175113],
       [0.9709076 , 0.31105124, 0.51209965, 0.38676135, 0.83070787],
       [0.37185289, 0.31056624, 0.9192465 , 0.56540854, 0.68075195]])

In [14]:
np.random.randn(6)#generates a 1D array which is a normal or 
                    # gaussian distribution centered in 0

array([ 0.72718502, -2.59108511,  1.35056403, -1.02067948,  2.14967237,
       -0.89068207])

In [15]:
np.random.randn(4,4)

array([[-0.27535422, -0.18395404, -0.90513377, -0.04524735],
       [-0.93184569,  1.5355849 ,  0.4073529 ,  1.33117089],
       [ 0.30762833, -1.69615624, -1.52599369,  0.23304436],
       [-3.07527717,  0.3726558 , -0.54074039,  0.57983254]])

In [16]:
np.random.randint(0, 100, 10) #(min value, max value, number of values to return)

array([30, 16,  5, 10, 96, 37, 60, 64, 47, 44])

Reshape for changing the arrays shape

In [17]:
arr = np.random.randint(0, 100, 25)

In [18]:
arr=arr.reshape(5, 5)

In [19]:
print(arr)

[[46 82 95 75 39]
 [20 47 40 61 64]
 [17  3 54 85  6]
 [71 80  9 95 53]
 [31  0 44 91 51]]


In [20]:
arr.max()#returns the max value

95

In [21]:
arr.argmax()#reutrns the location of the max value

2

In [22]:
arr.shape

(5, 5)

In [23]:
arr.argmax()

2

In [24]:
arr.dtype

dtype('int64')

INDEXING and SELECTION in np arrays

In [25]:
arr[4,4] #since a numpy array begins in 0, we selected the item of the 4th row and 4th col

51

In [26]:
arr[4, 0:4] #we selected the 4th row and the cols from 0 to 4

array([31,  0, 44, 91])

In [27]:
arr_copy = arr.copy() #we make a copy of the original array. Then we can make 
                        ## changes in the copy missaffecting the original one